export type MuscleGroup =
  | "Chest" | "Back" | "Shoulders" | "Biceps"
  | "Triceps" | "Quadriceps" | "Hamstrings"
  | "Glutes" | "Calves" | "Core" | "Full Body"
  | "Forearms" | "Adductors" | "Abductors" | "Neck" | "Cardio";

export type Equipment =
  | "Barbell" | "Dumbbell" | "Cable" | "Machine"
  | "Bodyweight" | "Kettlebell" | "Resistance Band"
  | "Smith Machine" | "Other";

export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export type Exercise = {
  id: string;
  name: string;
  primaryMuscle: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  tertiaryMuscles: MuscleGroup[];
  equipment: Equipment;
  difficulty: Difficulty;
  instructions: string[];
};

export const MUSCLE_COLORS: Record<string, string> = {
  Chest: "#FF6B6B",
  Back: "#4ECDC4",
  Shoulders: "#6C63FF",
  Biceps: "#00C9A7",
  Triceps: "#FF9F43",
  Quadriceps: "#54A0FF",
  Hamstrings: "#F368E0",
  Glutes: "#FF6B9D",
  Calves: "#48DBFB",
  Core: "#FECA57",
  "Full Body": "#A29BFE",
  Forearms: "#55EFC4",
  Adductors: "#FD79A8",
  Abductors: "#E17055",
  Neck: "#B2BEC3",
  Cardio: "#00B894",
};

export const MUSCLE_GROUPS: MuscleGroup[] = [
  "Chest", "Back", "Shoulders", "Biceps", "Triceps",
  "Quadriceps", "Hamstrings", "Glutes", "Calves", "Core",
  "Full Body", "Forearms", "Adductors", "Abductors", "Cardio",
];

export const EQUIPMENT_TYPES: Equipment[] = [
  "Barbell", "Dumbbell", "Cable", "Machine",
  "Bodyweight", "Kettlebell", "Resistance Band", "Smith Machine", "Other",
];

export const EXERCISES: Exercise[] = [
  // ── CHEST ──────────────────────────────────────────────────────────
  { id: "1", name: "Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Lie flat on bench, grip bar slightly wider than shoulder-width.", "Unrack bar, lower it to mid-chest under control.", "Press explosively back to start, lock out elbows at top."] },
  { id: "2", name: "Incline Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Set bench to 30–45°, grip bar wider than shoulder-width.", "Lower bar to upper chest, keeping elbows at ~45°.", "Press to full extension without flaring elbows excessively."] },
  { id: "3", name: "Decline Barbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Set bench to -15°, feet hooked under pads.", "Lower bar to lower chest in a controlled arc.", "Press back up to full lockout."] },
  { id: "4", name: "Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Lie flat, dumbbells at chest level with palms facing forward.", "Press dumbbells up and slightly together at the top.", "Lower slowly to chest level, feeling the stretch."] },
  { id: "5", name: "Incline Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Set bench 30–45°, hold dumbbells at upper chest.", "Press up and slightly inward, fully extending arms.", "Lower controlled to starting position."] },
  { id: "6", name: "Decline Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Set bench to decline, hold dumbbells at lower chest.", "Press dumbbells up to full extension.", "Lower slowly back to chest."] },
  { id: "7", name: "Dumbbell Flye", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Lie flat, hold dumbbells above chest with slight elbow bend.", "Lower dumbbells in a wide arc until you feel a chest stretch.", "Bring dumbbells back together squeezing chest at top."] },
  { id: "8", name: "Incline Dumbbell Flye", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Set bench 30–45°, hold dumbbells above upper chest.", "Open arms in a wide arc, feel the upper chest stretch.", "Squeeze chest to bring dumbbells back to start."] },
  { id: "9", name: "Cable Crossover High to Low", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Set cables high, stand in center with staggered stance.", "Pull handles down and together in an arc.", "Squeeze chest at bottom before returning."] },
  { id: "10", name: "Cable Crossover Low to High", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Set cables low, stand in center, slight forward lean.", "Pull handles up and together across body.", "Squeeze upper chest at top before returning."] },
  { id: "11", name: "Pec Deck Machine", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit upright, forearms on pads at chest height.", "Squeeze arms together until pads nearly touch.", "Slowly return to start with controlled resistance."] },
  { id: "12", name: "Chest Press Machine", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Adjust seat so handles are at chest level.", "Press handles forward to full extension.", "Return slowly without letting weight stack touch."] },
  { id: "13", name: "Push Up", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Shoulders"], tertiaryMuscles: ["Core"], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Hands slightly wider than shoulders, body in straight line.", "Lower chest toward floor, elbows at 45°.", "Push back to start keeping core tight."] },
  { id: "14", name: "Wide Push Up", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders"], tertiaryMuscles: ["Core"], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Place hands much wider than shoulder-width.", "Lower chest to floor with elbows flaring out.", "Push back up squeezing chest throughout."] },
  { id: "15", name: "Diamond Push Up", primaryMuscle: "Triceps", secondaryMuscles: ["Chest", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Form a diamond shape with thumbs and index fingers.", "Keep elbows close to body as you lower chest.", "Press back up fully extending arms."] },
  { id: "16", name: "Decline Push Up", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Elevate feet on bench, hands on floor.", "Lower chest toward floor maintaining plank position.", "Press back up to full arm extension."] },
  { id: "17", name: "Chest Dip", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Grip parallel bars, lean forward slightly.", "Lower body until upper arms are parallel to floor.", "Press back up without fully locking elbows."] },
  { id: "18", name: "Smith Machine Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Smith Machine", difficulty: "Beginner", instructions: ["Set bar to chest height, lie on bench below it.", "Unrack and lower bar to mid chest.", "Press up to full extension and re-rack."] },
  { id: "19", name: "Landmine Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Hold end of landmine barbell at shoulder height.", "Press the bar up and forward in an arc.", "Return to shoulder height under control."] },
  { id: "20", name: "Svend Press", primaryMuscle: "Chest", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Other", difficulty: "Beginner", instructions: ["Hold two plates together at chest height, pressing palms inward.", "Extend arms forward while squeezing plates together.", "Return to chest while maintaining inward squeeze."] },
  { id: "21", name: "Hex Press", primaryMuscle: "Chest", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Lie flat, press dumbbells together with neutral grip.", "Lower dumbbells to chest while keeping them pressed together.", "Press back up maintaining contact between dumbbells."] },
  { id: "22", name: "Single Arm Dumbbell Bench Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: ["Core"], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Lie flat holding one dumbbell at chest, other hand free.", "Press dumbbell up to full extension.", "Lower slowly, core braced against rotation."] },
  { id: "23", name: "Resistance Band Chest Press", primaryMuscle: "Chest", secondaryMuscles: ["Shoulders", "Triceps"], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Anchor band behind you at chest height.", "Hold handles at chest, step forward for tension.", "Press hands forward until arms extend fully."] },
  { id: "24", name: "Dumbbell Pullover", primaryMuscle: "Chest", secondaryMuscles: ["Back"], tertiaryMuscles: ["Triceps"], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Lie perpendicular to bench, upper back on pad.", "Hold one dumbbell over chest with both hands.", "Lower behind head in arc, then pull back over chest."] },
  { id: "25", name: "Incline Push Up", primaryMuscle: "Chest", secondaryMuscles: ["Triceps", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Place hands on elevated surface like a bench.", "Lower chest toward surface with straight body.", "Push back to start position."] },

  // ── BACK ───────────────────────────────────────────────────────────
  { id: "26", name: "Deadlift", primaryMuscle: "Back", secondaryMuscles: ["Hamstrings", "Glutes"], tertiaryMuscles: ["Core", "Quadriceps"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Stand with bar over mid-foot, hip-width stance.", "Hinge at hips, grip just outside legs, neutral spine.", "Drive through floor, lock hips and knees out at top."] },
  { id: "27", name: "Sumo Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], tertiaryMuscles: ["Quadriceps"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Wide stance, toes pointed out, grip inside legs.", "Sit into hips, chest up, push knees out over toes.", "Drive hips through, stand tall at lockout."] },
  { id: "28", name: "Romanian Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Stand holding bar at hip level, slight knee bend.", "Hinge forward pushing hips back, keeping bar close to legs.", "Drive hips forward to return to standing."] },
  { id: "29", name: "Rack Pull", primaryMuscle: "Back", secondaryMuscles: ["Hamstrings", "Glutes"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Advanced", instructions: ["Set bar in rack at knee height.", "Hinge forward to grip bar with neutral spine.", "Drive hips forward to full lockout."] },
  { id: "30", name: "Barbell Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Hinge to ~45°, overhand grip just wider than shoulder.", "Pull bar to lower chest, driving elbows back.", "Lower bar under control to full arm extension."] },
  { id: "31", name: "Pendlay Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Torso parallel to floor, bar on floor each rep.", "Explosively pull bar to lower chest.", "Lower bar all the way to floor before next rep."] },
  { id: "32", name: "T-Bar Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Straddle bar, hinge forward gripping handles.", "Pull bar to chest, squeezing shoulder blades.", "Lower with control."] },
  { id: "33", name: "Meadows Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Stand perpendicular to landmine bar, staggered stance.", "Grip end of bar, hinge at hips.", "Row bar to hip, driving elbow up and back."] },
  { id: "34", name: "Good Morning", primaryMuscle: "Back", secondaryMuscles: ["Hamstrings", "Glutes"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Bar on upper traps, hip-width stance.", "Hinge at hips, pushing them back, slight knee bend.", "Drive hips forward to return upright."] },
  { id: "35", name: "Pull Up", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: ["Shoulders", "Core"], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Dead hang from bar with overhand grip wider than shoulders.", "Pull chest to bar, driving elbows down and back.", "Lower with control to full hang."] },
  { id: "36", name: "Chin Up", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: ["Shoulders"], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Dead hang with underhand grip shoulder-width.", "Pull chin over bar, leading with chest.", "Lower to full dead hang."] },
  { id: "37", name: "Neutral Grip Pull Up", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Grip parallel handles with palms facing each other.", "Pull chest up to handles, elbows tracking close to body.", "Lower with control."] },
  { id: "38", name: "Lat Pulldown", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: ["Shoulders"], equipment: "Cable", difficulty: "Beginner", instructions: ["Sit with thighs under pads, overhand grip wider than shoulders.", "Pull bar to upper chest, leading with elbows.", "Return slowly to full arm extension."] },
  { id: "39", name: "Close Grip Lat Pulldown", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Use close grip attachment, sit upright.", "Pull handle to upper chest squeezing lats.", "Return to full extension."] },
  { id: "40", name: "Seated Cable Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps", "Shoulders"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Sit upright with slight torso lean, feet on platform.", "Pull handle to lower abdomen, squeezing shoulder blades.", "Return to full arm extension with slight torso lean."] },
  { id: "41", name: "Single Arm Dumbbell Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: ["Shoulders"], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Place opposite hand and knee on bench for support.", "Row dumbbell to hip level, elbow driving back.", "Lower to full extension."] },
  { id: "42", name: "Face Pull", primaryMuscle: "Shoulders", secondaryMuscles: ["Back"], tertiaryMuscles: ["Biceps"], equipment: "Cable", difficulty: "Beginner", instructions: ["Set cable at face height with rope attachment.", "Pull rope to face, hands going wide of ears.", "Squeeze rear delts before returning."] },
  { id: "43", name: "Straight Arm Pulldown", primaryMuscle: "Back", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Stand at cable, arms extended above, slight forward lean.", "With straight arms pull bar down to hips.", "Return slowly to start."] },
  { id: "44", name: "Hyperextension", primaryMuscle: "Back", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Position hips on pad, feet secured, cross arms over chest.", "Lower torso toward floor with controlled hinge.", "Raise torso to parallel with floor."] },
  { id: "45", name: "Cable Pull Through", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Back"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Face away from cable, rope between legs at low setting.", "Hinge at hips pushing them back, keeping rope tension.", "Drive hips forward to standing."] },
  { id: "46", name: "Barbell Shrug", primaryMuscle: "Back", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Hold bar at hip level, shoulder-width grip.", "Elevate shoulders as high as possible.", "Hold briefly at top, lower slowly."] },
  { id: "47", name: "Dumbbell Shrug", primaryMuscle: "Back", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at sides, stand tall.", "Raise shoulders straight up toward ears.", "Hold at top, lower with control."] },
  { id: "48", name: "Chest Supported Row", primaryMuscle: "Back", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Set incline bench to 45°, lie chest down.", "Row dumbbells up squeezing shoulder blades.", "Lower to full extension."] },
  { id: "49", name: "Reverse Hyperextension", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Back"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Intermediate", instructions: ["Lie face down on hyperextension bench, legs hanging.", "Raise legs until parallel to floor.", "Lower slowly."] },
  { id: "50", name: "Bird Dog", primaryMuscle: "Back", secondaryMuscles: ["Core", "Glutes"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Start on hands and knees, neutral spine.", "Extend opposite arm and leg simultaneously.", "Hold 2 seconds, return and repeat other side."] },

  // ── SHOULDERS ──────────────────────────────────────────────────────
  { id: "51", name: "Barbell Overhead Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], tertiaryMuscles: ["Core"], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Stand with bar at collarbone, grip just outside shoulders.", "Press bar overhead to full lockout.", "Lower under control to collarbone."] },
  { id: "52", name: "Seated Barbell Overhead Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Sit upright in rack, bar at collarbone.", "Press overhead to full extension.", "Lower bar to just below chin."] },
  { id: "53", name: "Push Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps", "Quadriceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Bar at collarbone, slight knee dip.", "Drive legs explosively and press bar overhead.", "Lower under control."] },
  { id: "54", name: "Dumbbell Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at shoulder height, palms forward.", "Press overhead until arms are fully extended.", "Lower to shoulder height."] },
  { id: "55", name: "Arnold Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Hold dumbbells in front at chin, palms facing you.", "Rotate palms out as you press overhead.", "Reverse rotation on the way down."] },
  { id: "56", name: "Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at sides, slight forward lean.", "Raise arms to shoulder height with slight bend in elbows.", "Lower slowly fighting gravity."] },
  { id: "57", name: "Seated Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Sit upright, dumbbells at sides.", "Raise arms to shoulder height, pinky slightly higher.", "Lower with control."] },
  { id: "58", name: "Cable Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Stand beside cable at lowest setting.", "Cross body and raise arm to shoulder height.", "Lower with control."] },
  { id: "59", name: "Front Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells in front of thighs, palms facing down.", "Raise one or both arms to shoulder height.", "Lower under control."] },
  { id: "60", name: "Rear Delt Fly", primaryMuscle: "Shoulders", secondaryMuscles: ["Back"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hinge forward at hips, dumbbells hanging below chest.", "Raise arms to shoulder height, squeezing rear delts.", "Lower slowly."] },
  { id: "61", name: "Cable Rear Delt Fly", primaryMuscle: "Shoulders", secondaryMuscles: ["Back"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Set cables at face height, cross cables.", "Pull handles wide apart at shoulder height.", "Squeeze rear delts at end range."] },
  { id: "62", name: "Upright Row", primaryMuscle: "Shoulders", secondaryMuscles: ["Back", "Biceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Hold bar with narrow overhand grip.", "Pull bar up along body to chin, elbows flaring wide.", "Lower with control."] },
  { id: "63", name: "Band Pull Apart", primaryMuscle: "Shoulders", secondaryMuscles: ["Back"], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Hold band at shoulder height in front, arms extended.", "Pull band apart, squeezing rear delts.", "Return to start."] },
  { id: "64", name: "Lu Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Hold dumbbells in front at hip level.", "Raise in a Y pattern with arms going up and out.", "Lower slowly."] },
  { id: "65", name: "Cuban Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Back"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Hang dumbbells at sides, row to elbow height.", "Rotate forearms up to vertical.", "Press overhead to full extension."] },
  { id: "66", name: "Machine Shoulder Press", primaryMuscle: "Shoulders", secondaryMuscles: ["Triceps"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Adjust seat so handles are at shoulder height.", "Press overhead to full extension.", "Return slowly without letting stack touch."] },
  { id: "67", name: "Resistance Band Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Stand on band, hold handles at sides.", "Raise arms to shoulder height.", "Lower under control."] },
  { id: "68", name: "Single Arm Cable Lateral Raise", primaryMuscle: "Shoulders", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Stand beside low cable, hold in opposite hand.", "Raise arm across body to shoulder height.", "Lower slowly."] },

  // ── BICEPS ─────────────────────────────────────────────────────────
  { id: "69", name: "Barbell Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Stand holding bar with underhand grip shoulder-width.", "Curl bar to shoulders, keeping elbows pinned to sides.", "Lower with control."] },
  { id: "70", name: "EZ Bar Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Grip EZ bar on inner curves, shoulder-width.", "Curl to shoulder height, elbows stationary.", "Lower fully to stretch."] },
  { id: "71", name: "Dumbbell Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at sides, palms forward.", "Curl both arms simultaneously to shoulder height.", "Squeeze at top, lower slowly."] },
  { id: "72", name: "Alternating Dumbbell Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at sides.", "Curl one arm at a time, supinating at the top.", "Alternate sides each rep."] },
  { id: "73", name: "Hammer Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells with neutral (thumbs up) grip.", "Curl up keeping neutral grip throughout.", "Lower with control."] },
  { id: "74", name: "Cross Body Hammer Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells at sides in neutral grip.", "Curl one dumbbell across body toward opposite shoulder.", "Alternate sides."] },
  { id: "75", name: "Incline Dumbbell Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Set bench to 45–60°, lie back holding dumbbells.", "Curl from full stretch, keeping upper arms vertical.", "Lower to full extension."] },
  { id: "76", name: "Concentration Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Sit on bench, elbow braced against inner thigh.", "Curl dumbbell to shoulder, squeezing hard at top.", "Lower to full extension."] },
  { id: "77", name: "Cable Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Stand at low cable with bar or EZ attachment.", "Curl handle to shoulder height, elbows pinned.", "Return to full extension."] },
  { id: "78", name: "Preacher Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Rest upper arms on preacher pad, hold bar.", "Curl bar up, squeezing bicep at top.", "Lower to near full extension, don't hyperextend."] },
  { id: "79", name: "Spider Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Lie face down on incline bench, arms hanging.", "Curl bar to forehead, keeping upper arms vertical.", "Lower slowly to full stretch."] },
  { id: "80", name: "Zottman Curl", primaryMuscle: "Biceps", secondaryMuscles: ["Forearms"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Curl with supinated grip on the way up.", "Rotate to pronated grip at top.", "Lower with pronated grip (works forearms)."] },
  { id: "81", name: "Bayesian Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Stand facing away from cable at hip level.", "Step forward, curl handle to shoulder.", "Feel deep stretch at bottom of each rep."] },
  { id: "82", name: "Overhead Cable Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Set cables at face height on both sides.", "Curl handles toward head from an outstretched position.", "Squeeze at peak contraction."] },
  { id: "83", name: "Resistance Band Curl", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Stand on band, hold handles at sides.", "Curl handles to shoulders, elbows stationary.", "Lower slowly."] },
  { id: "84", name: "Reverse Curl", primaryMuscle: "Forearms", secondaryMuscles: ["Biceps"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Hold bar with overhand grip shoulder-width.", "Curl bar to shoulder height.", "Lower with control."] },
  { id: "85", name: "21s", primaryMuscle: "Biceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["7 reps from bottom to midpoint, 7 from midpoint to top, 7 full reps.", "Keep elbows pinned throughout.", "No rest between the three phases."] },

  // ── TRICEPS ────────────────────────────────────────────────────────
  { id: "86", name: "Close Grip Bench Press", primaryMuscle: "Triceps", secondaryMuscles: ["Chest", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Grip bar shoulder-width, elbows close to body.", "Lower bar to lower chest, elbows at 45°.", "Press to full lockout."] },
  { id: "87", name: "Skull Crusher", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Lie flat, bar above chest, narrow grip.", "Lower bar to forehead by bending only at elbows.", "Extend arms fully back to start."] },
  { id: "88", name: "EZ Bar Skull Crusher", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Lie flat with EZ bar, grip on inner curves.", "Lower toward forehead bending only at elbows.", "Extend fully."] },
  { id: "89", name: "Dumbbell Skull Crusher", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Lie flat, dumbbells above chest, palms facing each other.", "Lower to temples by bending elbows only.", "Extend back to start."] },
  { id: "90", name: "Tricep Pushdown", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Stand at high cable, overhand grip on bar.", "Push down until arms fully extended, elbows pinned.", "Return to 90° before next rep."] },
  { id: "91", name: "Rope Pushdown", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Attach rope to high cable.", "Push down and flare rope out at bottom.", "Return to 90°."] },
  { id: "92", name: "Overhead Cable Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Face away from cable, hold rope overhead.", "Extend arms forward until fully straight.", "Return to start position."] },
  { id: "93", name: "Overhead Dumbbell Tricep Extension", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold one dumbbell overhead with both hands.", "Lower behind head bending only at elbows.", "Extend back to start."] },
  { id: "94", name: "Tricep Kickback", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hinge forward, upper arm parallel to floor.", "Extend arm back until fully straight.", "Lower to 90° and repeat."] },
  { id: "95", name: "Tricep Dip", primaryMuscle: "Triceps", secondaryMuscles: ["Chest", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Grip parallel bars, stay upright to target triceps.", "Lower until elbows reach 90°.", "Press back to full lockout."] },
  { id: "96", name: "Bench Dip", primaryMuscle: "Triceps", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Hands on bench behind you, feet extended.", "Lower body by bending elbows to 90°.", "Press back up to full extension."] },
  { id: "97", name: "JM Press", primaryMuscle: "Triceps", secondaryMuscles: ["Chest"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Advanced", instructions: ["Lie flat, close grip, lower bar to neck with elbows up.", "Hybrid movement between skull crusher and close grip press.", "Press back to full extension."] },
  { id: "98", name: "Tate Press", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Lie flat, dumbbells touching above chest, elbows out.", "Lower dumbbell ends to chest by flaring elbows.", "Press back up keeping dumbbell ends in contact."] },
  { id: "99", name: "Floor Press", primaryMuscle: "Triceps", secondaryMuscles: ["Chest", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Lie on floor with bar over chest.", "Lower until triceps touch floor.", "Press back to lockout."] },
  { id: "100", name: "Resistance Band Pushdown", primaryMuscle: "Triceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Anchor band overhead, grip ends.", "Push down to full extension.", "Return to 90° slowly."] },

  // ── QUADRICEPS ─────────────────────────────────────────────────────
  { id: "101", name: "Barbell Back Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: ["Core", "Calves"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Bar on upper traps, hip-width stance, toes slightly out.", "Sit into squat keeping chest up and knees tracking over toes.", "Drive through heels to lockout at top."] },
  { id: "102", name: "Front Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: ["Core"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Bar on front delts, elbows high, upright torso.", "Squat keeping torso vertical, knees forward.", "Drive up to lockout."] },
  { id: "103", name: "Hack Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Intermediate", instructions: ["Shoulders against pads, feet low on platform.", "Lower until thighs are parallel.", "Push through mid-foot back to start."] },
  { id: "104", name: "Leg Press", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Seat reclined, feet shoulder-width on platform.", "Lower platform until knees reach 90°.", "Press away to near full extension, don't lock out."] },
  { id: "105", name: "Bulgarian Split Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: ["Core"], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Rear foot on bench, front foot forward.", "Lower back knee toward floor, torso upright.", "Drive through front heel to return."] },
  { id: "106", name: "Lunge", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Stand tall, step forward with one foot.", "Lower back knee toward floor.", "Push back to standing and repeat."] },
  { id: "107", name: "Walking Lunge", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Hold dumbbells at sides, step forward into lunge.", "Drive front foot to bring back foot forward.", "Continue alternating legs forward."] },
  { id: "108", name: "Reverse Lunge", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Step backward into lunge.", "Lower back knee toward floor.", "Push front foot to return to standing."] },
  { id: "109", name: "Leg Extension", primaryMuscle: "Quadriceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit with legs under pad, back against seat.", "Extend legs to near full lockout.", "Lower with control."] },
  { id: "110", name: "Goblet Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes"], tertiaryMuscles: ["Core"], equipment: "Kettlebell", difficulty: "Beginner", instructions: ["Hold kettlebell at chest with both hands.", "Squat with upright torso, elbows inside knees.", "Drive up to standing."] },
  { id: "111", name: "Step Up", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells, step one foot onto elevated surface.", "Drive through front heel to bring other foot up.", "Step back down and repeat."] },
  { id: "112", name: "Sissy Squat", primaryMuscle: "Quadriceps", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Hold support, rise onto toes.", "Lean back and lower knees toward floor.", "Drive back up through quads."] },
  { id: "113", name: "Box Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Set box at or below parallel behind you.", "Squat back onto box, pausing briefly.", "Drive up explosively."] },
  { id: "114", name: "Smith Machine Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes"], tertiaryMuscles: [], equipment: "Smith Machine", difficulty: "Beginner", instructions: ["Feet forward of bar, shoulder-width.", "Squat to parallel on the guided path.", "Press back to standing."] },
  { id: "115", name: "Pistol Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Hamstrings"], tertiaryMuscles: ["Core"], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Stand on one foot, other leg extended.", "Lower into full squat on one leg.", "Drive back up to standing."] },
  { id: "116", name: "Jump Squat", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Calves"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Squat to parallel.", "Explode upward leaving ground.", "Land softly with bent knees."] },
  { id: "117", name: "Lateral Lunge", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Adductors"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Stand tall, step wide to one side.", "Bend stepping knee while other stays straight.", "Push off to return, repeat other side."] },

  // ── HAMSTRINGS ─────────────────────────────────────────────────────
  { id: "118", name: "Dumbbell Romanian Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold dumbbells in front of thighs.", "Hinge at hips, pushing them back, soft knee bend.", "Drive hips forward to return to standing."] },
  { id: "119", name: "Single Leg Romanian Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Core"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Stand on one leg, hold dumbbell in opposite hand.", "Hinge forward, extending free leg behind.", "Return to standing, squeeze glute at top."] },
  { id: "120", name: "Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Lie face down, pad just above ankles.", "Curl heels toward glutes.", "Lower with control."] },
  { id: "121", name: "Seated Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit upright, pads against lower legs.", "Curl legs down and back.", "Return slowly."] },
  { id: "122", name: "Nordic Curl", primaryMuscle: "Hamstrings", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Kneel with feet secured, arms at sides.", "Lower body forward as slowly as possible.", "Catch with hands and push back to start."] },
  { id: "123", name: "Stiff Leg Deadlift", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Back"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Stand with bar at hips, minimal knee bend.", "Lower bar along legs with flat back.", "Return to standing."] },
  { id: "124", name: "Glute Ham Raise", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Advanced", instructions: ["Secure feet on GHD machine, torso parallel to floor.", "Lower controlled then powerfully contract hamstrings to rise.", "Keep hips in line."] },
  { id: "125", name: "Swiss Ball Leg Curl", primaryMuscle: "Hamstrings", secondaryMuscles: ["Glutes", "Core"], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Lie on back, heels on Swiss ball.", "Raise hips into bridge position.", "Curl ball toward glutes, then extend."] },

  // ── GLUTES ─────────────────────────────────────────────────────────
  { id: "126", name: "Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Upper back on bench, bar across hips.", "Drive hips up until body is in line from knees to shoulders.", "Lower with control."] },
  { id: "127", name: "Barbell Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Load bar, position on hip crease with pad.", "Drive hips explosively to full extension.", "Squeeze glutes at top for 1 second."] },
  { id: "128", name: "Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, knees bent, feet flat.", "Drive hips up squeezing glutes at top.", "Lower slowly."] },
  { id: "129", name: "Single Leg Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Core"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Upper back on bench, one leg extended.", "Drive hips up on working leg only.", "Lower and repeat."] },
  { id: "130", name: "Cable Kickback", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Attach ankle cuff to low cable.", "Hinge slightly, kick leg straight back.", "Squeeze glute at end range."] },
  { id: "131", name: "Donkey Kick", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["On all fours, keep core tight.", "Kick one leg up, knee bent at 90°.", "Squeeze glute at top, lower and repeat."] },
  { id: "132", name: "Fire Hydrant", primaryMuscle: "Glutes", secondaryMuscles: ["Abductors"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["On all fours, core braced.", "Lift knee out to the side to hip height.", "Lower with control."] },
  { id: "133", name: "Banded Glute Bridge", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Band above knees, lie on back.", "Push knees out against band while driving hips up.", "Squeeze glutes at top."] },
  { id: "134", name: "Frog Pump", primaryMuscle: "Glutes", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, soles of feet together, knees out.", "Drive hips up squeezing glutes.", "Lower and repeat for high reps."] },
  { id: "135", name: "Smith Machine Hip Thrust", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings"], tertiaryMuscles: [], equipment: "Smith Machine", difficulty: "Intermediate", instructions: ["Set smith machine low, position bar on hips.", "Drive hips up to full extension.", "Lower under control."] },

  // ── CALVES ─────────────────────────────────────────────────────────
  { id: "136", name: "Standing Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Shoulders under pads, balls of feet on platform.", "Rise up on toes as high as possible.", "Lower heel below platform for full stretch."] },
  { id: "137", name: "Seated Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit with pads on knees, feet on platform.", "Raise heels as high as possible.", "Lower for full stretch."] },
  { id: "138", name: "Donkey Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Intermediate", instructions: ["Bend at hips, pads on lower back.", "Raise on toes to full extension.", "Lower for deep stretch."] },
  { id: "139", name: "Single Leg Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Stand on one foot on edge of step.", "Rise onto toes as high as possible.", "Lower heel below step."] },
  { id: "140", name: "Leg Press Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["On leg press, extend legs fully, only balls of feet on platform.", "Press platform away with toes only.", "Return to deep stretch position."] },
  { id: "141", name: "Tibialis Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Stand with heels on floor, back against wall.", "Raise toes as high as possible.", "Lower and repeat for shin/tibialis strength."] },
  { id: "142", name: "Barbell Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Bar on traps, feet shoulder-width on plates.", "Rise as high as possible.", "Lower for full stretch."] },
  { id: "143", name: "Reverse Calf Raise", primaryMuscle: "Calves", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Stand with heels on edge of step, toes hanging.", "Raise toes up as high as possible.", "Lower slowly."] },

  // ── CORE ───────────────────────────────────────────────────────────
  { id: "144", name: "Crunch", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, knees bent, hands behind head.", "Curl shoulders off floor, exhaling.", "Lower with control."] },
  { id: "145", name: "Sit Up", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, knees bent, feet secured.", "Sit fully upright, keeping core engaged.", "Lower with control."] },
  { id: "146", name: "Leg Raise", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie flat, hands under glutes for support.", "Raise straight legs to 90°.", "Lower slowly without letting feet touch floor."] },
  { id: "147", name: "Hanging Leg Raise", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Hang from pull-up bar.", "Raise straight legs to 90°.", "Lower with control."] },
  { id: "148", name: "Toes to Bar", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Hang from pull-up bar.", "Raise straight legs until toes touch bar.", "Lower with control."] },
  { id: "149", name: "Plank", primaryMuscle: "Core", secondaryMuscles: ["Shoulders", "Back"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Forearms on floor, body in straight line.", "Squeeze glutes and brace abs.", "Hold position, don't let hips sag."] },
  { id: "150", name: "Side Plank", primaryMuscle: "Core", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on side, forearm on floor.", "Raise hips to form straight line.", "Hold position, keep hips elevated."] },
  { id: "151", name: "Ab Wheel Rollout", primaryMuscle: "Core", secondaryMuscles: ["Shoulders", "Back"], tertiaryMuscles: [], equipment: "Other", difficulty: "Advanced", instructions: ["Kneel with wheel in hands.", "Roll forward extending arms, keeping core braced.", "Pull back to start using core."] },
  { id: "152", name: "Cable Crunch", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Kneel at cable, rope at neck.", "Crunch down rounding lower back.", "Return to start."] },
  { id: "153", name: "Bicycle Crunch", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, hands behind head.", "Bring opposite elbow to opposite knee.", "Alternate sides in a pedaling motion."] },
  { id: "154", name: "Russian Twist", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Sit with knees bent, lean back 45°.", "Twist torso side to side.", "Keep feet elevated for added difficulty."] },
  { id: "155", name: "Mountain Climber", primaryMuscle: "Core", secondaryMuscles: ["Shoulders", "Chest"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Start in push-up position.", "Drive knees to chest alternately.", "Keep hips level and core tight."] },
  { id: "156", name: "Dragon Flag", primaryMuscle: "Core", secondaryMuscles: ["Back"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Lie on bench, grip behind head.", "Raise body to vertical supported only by shoulders.", "Lower as straight as possible."] },
  { id: "157", name: "Pallof Press", primaryMuscle: "Core", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Stand sideways to cable at chest height.", "Hold handle at chest, press out to full extension.", "Return to chest, resist rotation throughout."] },
  { id: "158", name: "Dead Bug", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Lie on back, arms and legs up at 90°.", "Lower opposite arm and leg toward floor.", "Return and repeat other side."] },
  { id: "159", name: "Hollow Body Hold", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Lie on back, arms overhead, legs extended.", "Raise arms, legs, and shoulders off floor.", "Hold pressing lower back into floor."] },
  { id: "160", name: "V-Up", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Lie flat, arms overhead.", "Simultaneously raise arms and legs to touch hands to feet.", "Lower with control."] },
  { id: "161", name: "Woodchop", primaryMuscle: "Core", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Intermediate", instructions: ["Set cable high on one side.", "Pull handle diagonally down across body.", "Return and repeat same side."] },
  { id: "162", name: "Landmine Rotation", primaryMuscle: "Core", secondaryMuscles: ["Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Intermediate", instructions: ["Hold end of landmine bar at chest height.", "Rotate to sweep bar side to side.", "Keep hips square, rotate from core."] },
  { id: "163", name: "Hanging Knee Raise", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Hang from pull-up bar.", "Raise knees to chest.", "Lower with control."] },
  { id: "164", name: "Weighted Crunch", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Lie on back holding plate at chest.", "Curl shoulders off floor.", "Lower with control."] },
  { id: "165", name: "Decline Sit Up", primaryMuscle: "Core", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Intermediate", instructions: ["Secure feet on decline bench.", "Sit up fully from declined position.", "Lower with control."] },

  // ── FULL BODY ──────────────────────────────────────────────────────
  { id: "166", name: "Kettlebell Swing", primaryMuscle: "Glutes", secondaryMuscles: ["Hamstrings", "Back"], tertiaryMuscles: ["Core", "Shoulders"], equipment: "Kettlebell", difficulty: "Intermediate", instructions: ["Hinge at hips, grip kettlebell between legs.", "Explosively drive hips forward swinging bell to chest height.", "Let bell fall, hinge and repeat."] },
  { id: "167", name: "Burpee", primaryMuscle: "Full Body", secondaryMuscles: ["Chest", "Shoulders"], tertiaryMuscles: ["Core", "Quadriceps"], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["From standing, drop hands to floor.", "Jump feet back to push-up position, perform push-up.", "Jump feet to hands, then jump up with hands overhead."] },
  { id: "168", name: "Box Jump", primaryMuscle: "Quadriceps", secondaryMuscles: ["Glutes", "Calves"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Stand in front of box, slight squat.", "Explode upward landing softly on box.", "Step or jump back down."] },
  { id: "169", name: "Power Clean", primaryMuscle: "Full Body", secondaryMuscles: ["Back", "Shoulders"], tertiaryMuscles: ["Quadriceps", "Glutes"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Deadlift bar off floor with speed.", "Explosively extend hips and shrug.", "Drop under bar catching in front rack position."] },
  { id: "170", name: "Turkish Get Up", primaryMuscle: "Full Body", secondaryMuscles: ["Core", "Shoulders"], tertiaryMuscles: [], equipment: "Kettlebell", difficulty: "Advanced", instructions: ["Lie holding kettlebell pressed overhead.", "Using free hand and leg, rise to standing keeping bell locked out.", "Reverse the movement to lie back down."] },
  { id: "171", name: "Thruster", primaryMuscle: "Full Body", secondaryMuscles: ["Quadriceps", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Advanced", instructions: ["Bar in front rack, squat to parallel.", "Drive up explosively using leg drive.", "Press bar overhead to full lockout in one motion."] },
  { id: "172", name: "Farmers Walk", primaryMuscle: "Full Body", secondaryMuscles: ["Core", "Back"], tertiaryMuscles: ["Calves"], equipment: "Dumbbell", difficulty: "Beginner", instructions: ["Hold heavy dumbbells or kettlebells at sides.", "Walk with upright torso and short stride.", "Keep core braced and shoulders back."] },
  { id: "173", name: "Sled Push", primaryMuscle: "Full Body", secondaryMuscles: ["Quadriceps", "Glutes"], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Load sled, lean forward gripping poles.", "Drive through legs pushing sled forward.", "Keep back flat and drive with full extension."] },
  { id: "174", name: "Battle Ropes", primaryMuscle: "Full Body", secondaryMuscles: ["Shoulders", "Core"], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Hold rope ends with firm grip, slight squat.", "Alternately slam ropes creating waves.", "Keep core tight and drive from legs."] },
  { id: "175", name: "Kettlebell Snatch", primaryMuscle: "Full Body", secondaryMuscles: ["Shoulders", "Back"], tertiaryMuscles: ["Core"], equipment: "Kettlebell", difficulty: "Advanced", instructions: ["Swing kettlebell back between legs.", "Explosively hike and punch hand through overhead.", "Lock out at top with bell over forearm."] },
  { id: "176", name: "Clean and Press", primaryMuscle: "Full Body", secondaryMuscles: ["Shoulders", "Back"], tertiaryMuscles: ["Quadriceps"], equipment: "Barbell", difficulty: "Advanced", instructions: ["Clean bar from floor to front rack.", "Dip slightly and drive bar overhead.", "Lower under control."] },
  { id: "177", name: "Medicine Ball Slam", primaryMuscle: "Full Body", secondaryMuscles: ["Core", "Shoulders"], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Hold ball overhead, fully extended.", "Slam ball into floor as hard as possible.", "Catch on bounce and repeat."] },
  { id: "178", name: "Broad Jump", primaryMuscle: "Full Body", secondaryMuscles: ["Quadriceps", "Glutes"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Intermediate", instructions: ["Squat and swing arms back.", "Explode forward jumping as far as possible.", "Land softly with bent knees."] },
  { id: "179", name: "Hang Clean", primaryMuscle: "Full Body", secondaryMuscles: ["Back", "Shoulders"], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Advanced", instructions: ["Hold bar at hip level.", "Explosively extend hips and pull bar up.", "Drop under into front squat catching bar."] },
  { id: "180", name: "Dumbbell Thruster", primaryMuscle: "Full Body", secondaryMuscles: ["Quadriceps", "Shoulders"], tertiaryMuscles: [], equipment: "Dumbbell", difficulty: "Intermediate", instructions: ["Hold dumbbells at shoulders.", "Squat to parallel.", "Drive up and press dumbbells overhead in one motion."] },

  // ── FOREARMS ───────────────────────────────────────────────────────
  { id: "181", name: "Wrist Curl", primaryMuscle: "Forearms", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Forearms on bench, palms up, bar in hands.", "Lower bar rolling to fingertips.", "Curl wrists back up."] },
  { id: "182", name: "Reverse Wrist Curl", primaryMuscle: "Forearms", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Barbell", difficulty: "Beginner", instructions: ["Forearms on bench, palms down.", "Raise bar by extending wrists.", "Lower with control."] },
  { id: "183", name: "Plate Pinch", primaryMuscle: "Forearms", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Other", difficulty: "Beginner", instructions: ["Pinch two plates between fingers and thumb.", "Hold for time.", "Switch hands."] },
  { id: "184", name: "Dead Hang", primaryMuscle: "Forearms", secondaryMuscles: ["Back", "Shoulders"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Grip pull-up bar with both hands.", "Hang with body relaxed.", "Hold for time, increasing duration over sessions."] },
  { id: "185", name: "Wrist Roller", primaryMuscle: "Forearms", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Other", difficulty: "Intermediate", instructions: ["Hold roller with arms extended.", "Roll weight up by alternating wrist rotations.", "Slowly unroll to lower."] },

  // ── ADDUCTORS / ABDUCTORS ──────────────────────────────────────────
  { id: "186", name: "Hip Abduction Machine", primaryMuscle: "Abductors", secondaryMuscles: ["Glutes"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit in machine, pads against outer thighs.", "Push legs outward against resistance.", "Return slowly to start."] },
  { id: "187", name: "Hip Adduction Machine", primaryMuscle: "Adductors", secondaryMuscles: [], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit in machine, pads against inner thighs.", "Squeeze legs together against resistance.", "Return slowly."] },
  { id: "188", name: "Cable Hip Abduction", primaryMuscle: "Abductors", secondaryMuscles: ["Glutes"], tertiaryMuscles: [], equipment: "Cable", difficulty: "Beginner", instructions: ["Attach ankle cuff to low cable.", "Stand sideways, kick leg out to the side.", "Return with control."] },
  { id: "189", name: "Banded Clamshell", primaryMuscle: "Abductors", secondaryMuscles: ["Glutes"], tertiaryMuscles: [], equipment: "Resistance Band", difficulty: "Beginner", instructions: ["Band above knees, lie on side with knees bent.", "Rotate top knee up like a clamshell.", "Return with control."] },
  { id: "190", name: "Copenhagen Plank", primaryMuscle: "Adductors", secondaryMuscles: ["Core"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Advanced", instructions: ["Top foot on bench, bottom leg hanging.", "Hold side plank position.", "Drop bottom knee to touch floor optionally."] },

  // ── CARDIO ─────────────────────────────────────────────────────────
  { id: "191", name: "Jump Rope", primaryMuscle: "Cardio", secondaryMuscles: ["Calves", "Shoulders"], tertiaryMuscles: [], equipment: "Other", difficulty: "Beginner", instructions: ["Hold handles, rope behind feet.", "Swing rope overhead and jump over it.", "Keep jumps small and rhythm consistent."] },
  { id: "192", name: "High Knees", primaryMuscle: "Cardio", secondaryMuscles: ["Core", "Quadriceps"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Run in place driving knees to chest.", "Pump arms in opposition.", "Maintain fast pace."] },
  { id: "193", name: "Jumping Jack", primaryMuscle: "Cardio", secondaryMuscles: ["Shoulders", "Calves"], tertiaryMuscles: [], equipment: "Bodyweight", difficulty: "Beginner", instructions: ["Start standing, feet together, arms at sides.", "Jump spreading feet wide while raising arms overhead.", "Jump back to start."] },
  { id: "194", name: "Rowing Machine", primaryMuscle: "Cardio", secondaryMuscles: ["Back", "Legs"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Beginner", instructions: ["Sit on machine, grip handle with overhand grip.", "Drive legs, lean back, then pull handle to chest.", "Return extending arms first, then lean forward, then bend knees."] },
  { id: "195", name: "Assault Bike", primaryMuscle: "Cardio", secondaryMuscles: ["Full Body"], tertiaryMuscles: [], equipment: "Machine", difficulty: "Intermediate", instructions: ["Sit on bike, grip handles.", "Pedal legs and push/pull handles simultaneously.", "Maintain target pace or go all-out for intervals."] },
];
